/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class design_1 extends javax.swing.JPanel {

    /**
     * Creates new form design_1
     */
    public design_1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1 = new javax.swing.JPanel();
        photo = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jp2 = new javax.swing.JPanel();
        photo1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bt = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        photo2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jp1.setLayout(null);

        photo.setText("jLabel1");
        jp1.add(photo);
        photo.setBounds(50, 80, 130, 150);

        date.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        date.setText("jLabel1");
        jp1.add(date);
        date.setBounds(130, 230, 80, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Date");
        jp1.add(jLabel1);
        jLabel1.setBounds(20, 240, 60, 30);

        jButton1.setText("BUTTON");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jp1.add(jButton1);
        jButton1.setBounds(160, 30, 80, 40);

        jLabel2.setText("ABOUT MOVIE ");
        jp1.add(jLabel2);
        jLabel2.setBounds(50, 280, 100, 40);

        jp2.setLayout(null);

        photo1.setText("jLabel1");
        jp2.add(photo1);
        photo1.setBounds(50, 80, 130, 150);

        date1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        date1.setText("jLabel1");
        jp2.add(date1);
        date1.setBounds(130, 230, 80, 40);

        title2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        title2.setText("jLabel1");
        jp2.add(title2);
        title2.setBounds(50, 16, 80, 70);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Date");
        jp2.add(jLabel3);
        jLabel3.setBounds(20, 240, 60, 30);

        jButton2.setText("BUTTON");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jp2.add(jButton2);
        jButton2.setBounds(160, 30, 80, 40);

        jLabel4.setText("ABOUT MOVIE ");
        jp2.add(jLabel4);
        jLabel4.setBounds(50, 280, 100, 40);

        jScrollPane1.setViewportView(jp2);

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        setLayout(null);

        bt.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionPerformed(evt);
            }
        });
        add(bt);
        bt.setBounds(200, 30, 70, 40);

        title.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        title.setText("TITLE");
        add(title);
        title.setBounds(20, 20, 150, 50);
        add(photo2);
        photo2.setBounds(60, 80, 180, 160);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Date");
        add(jLabel5);
        jLabel5.setBounds(30, 250, 60, 30);

        date2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        add(date2);
        date2.setBounds(110, 250, 170, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("DESCRIPTION");
        add(jLabel6);
        jLabel6.setBounds(60, 280, 140, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane7.setViewportView(jTextArea1);

        add(jScrollPane7);
        jScrollPane7.setBounds(20, 310, 250, 90);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bt;
    public javax.swing.JLabel date;
    public javax.swing.JLabel date1;
    public javax.swing.JLabel date2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JPanel jp1;
    public javax.swing.JPanel jp2;
    public javax.swing.JLabel photo;
    public javax.swing.JLabel photo1;
    public javax.swing.JLabel photo2;
    public javax.swing.JLabel title;
    public javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
