
import VMM.DBloader;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class edit_profile extends javax.swing.JFrame {

    /**
     * Creates new form edit_profile
     */
    JLabel plb;
    File ph = null;
    
    public edit_profile() {
        initComponents();
         call();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
          int h=(int)d.getHeight();
          int w=(int)d.getWidth();
         plb = new JLabel();
    plb.setBounds(0, 0, w, h);
    
    ImageIcon ic = new ImageIcon("src\\myuploads\\purple.png");
    Image ic1 = ic.getImage().getScaledInstance(plb.getWidth(), plb.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon ic2 = new ImageIcon(ic1);
    plb.setIcon(ic2);
    
    
//    ImageIcon ic41 = new ImageIcon("src\\myuploads\\grey.jpg");
//        Image ic51 = ic41.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon ic61 = new ImageIcon(ic51);
//        jLabel1.setIcon(ic61);
    
    add(plb);
    setSize(w, h);
    
    ImageIcon ic4 = new ImageIcon("src\\myuploads\\left-arrow1.png");
        Image ic5 = ic4.getImage().getScaledInstance(jb.getWidth(), jb.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic6 = new ImageIcon(ic5);
        jb.setIcon(ic6);
    
    
    setVisible(true);
          //setSize(w,h);
         
          //setVisible(true);
           
          
    }
void call()
    {
         try {
             ResultSet rs=DBloader.executeSQL("select * from user where email='"+global.email+"'");
             if(rs.next())
             {
                 String name=rs.getString("username");
                
                 String contact=rs.getString("contact");
          
                 String photo1=rs.getString("photo");
                 tf1.setText(name);
                 tf2.setText(contact);
                
                 
                  ImageIcon ic=new ImageIcon(photo1);
           Image icl=ic.getImage().getScaledInstance(photo.getWidth(), photo.getHeight(), Image.SCALE_SMOOTH);
           ImageIcon ic2=new ImageIcon(icl);
           
           photo.setIcon(ic2);
             }
         } catch (Exception ex) {
             ex.printStackTrace();
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        mlb1 = new javax.swing.JButton();
        plb1 = new javax.swing.JButton();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        jb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lb.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        lb.setForeground(new java.awt.Color(255, 255, 255));
        lb.setText("    EDIT PROFILE");
        lb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(lb);
        lb.setBounds(470, 220, 490, 80);

        lb1.setBackground(new java.awt.Color(255, 0, 0));
        lb1.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setText("NAME");
        getContentPane().add(lb1);
        lb1.setBounds(340, 320, 200, 40);

        lb2.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        lb2.setForeground(new java.awt.Color(255, 255, 255));
        lb2.setText("MOBILE NO. ");
        getContentPane().add(lb2);
        lb2.setBounds(280, 410, 340, 40);

        lb3.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        lb3.setForeground(new java.awt.Color(255, 255, 255));
        lb3.setText("PHOTO");
        getContentPane().add(lb3);
        lb3.setBounds(330, 500, 220, 50);
        getContentPane().add(photo);
        photo.setBounds(1000, 340, 250, 230);

        mlb1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        mlb1.setForeground(new java.awt.Color(51, 0, 51));
        mlb1.setText("EDIT");
        mlb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlb1ActionPerformed(evt);
            }
        });
        getContentPane().add(mlb1);
        mlb1.setBounds(420, 630, 360, 60);

        plb1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        plb1.setForeground(new java.awt.Color(51, 0, 51));
        plb1.setText("CHOOSE");
        plb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plb1ActionPerformed(evt);
            }
        });
        getContentPane().add(plb1);
        plb1.setBounds(620, 500, 290, 50);

        tf1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(tf1);
        tf1.setBounds(620, 330, 290, 50);

        tf2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(tf2);
        tf2.setBounds(620, 410, 290, 50);

        jb.setBackground(new java.awt.Color(204, 204, 204));
        jb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActionPerformed(evt);
            }
        });
        getContentPane().add(jb);
        jb.setBounds(20, 30, 100, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mlb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlb1ActionPerformed
        // TODO add your handling code here:
        String name = tf1.getText().trim();
       
  
        String contact = (tf2.getText().trim());
       
        
        try {
            // TODO add your handling code here:
            // ResultSet rs = DBloader.executeSQL("select * from admin_cars ");

            ResultSet rs = DBloader.executeSQL("Select * from user where email ='"+global.email+"'");
            if(rs.next()){
            
           
            rs.updateString("username", name);                      
            
            rs.updateString("contact", contact);
            
          
            if(ph!=null)
            {
                String path = SaveFile.saveFile(ph);
                rs.updateString("photo", path);
            }
              rs.updateRow();
            JOptionPane.showMessageDialog(this, "Success");
}
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        

    
    }//GEN-LAST:event_mlb1ActionPerformed

    private void plb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plb1ActionPerformed
        // TODO add your handling code here:
JFileChooser jfc=new JFileChooser();
        int ans=jfc.showOpenDialog(this);
        if(ans==JFileChooser.APPROVE_OPTION)
        {
              ph = jfc.getSelectedFile();
           ImageIcon ic=new ImageIcon(ph.getPath());
           Image icl=ic.getImage().getScaledInstance(photo.getWidth(), photo.getHeight(), Image.SCALE_SMOOTH);
           ImageIcon ic2=new ImageIcon(icl);
           
           photo.setIcon(ic2);

        }
    }//GEN-LAST:event_plb1ActionPerformed

    private void jbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActionPerformed
        // TODO add your handling code here:
         home_page obj = new home_page();
        setVisible(true);
        dispose();
    }//GEN-LAST:event_jbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JButton mlb1;
    private javax.swing.JLabel photo;
    private javax.swing.JButton plb1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
