
import VMM.DBloader;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;
import javax.mail.*;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.UIManager;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class forgot_password extends javax.swing.JFrame {

    /**
     * Creates new form forgot_password
     */
//     JLabel lb11 = new javax.swing.JLabel();
      String otp;
    ResultSet rs;
    JLabel plb;
    public forgot_password() {
        initComponents();
        plb = new JLabel();
         Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
          int h=(int)d.getHeight();
          int w=(int)d.getWidth();
          setSize(w,h);
          
          jLabel2.setVisible(false);
                tf2.setVisible(false);
                jButton2.setVisible(false);
           plb.setBounds(0, 0, w, h);
    
    ImageIcon ic = new ImageIcon("src\\myuploads\\flat-lay-cinema-.jpg");
    Image ic1 = ic.getImage().getScaledInstance(plb.getWidth(), plb.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon ic2 = new ImageIcon(ic1);
    plb.setIcon(ic2);
    
    add(plb);
    setSize(w, h);
         setVisible(true);
         
         ImageIcon ic4 = new ImageIcon("src\\myuploads\\left-arrow1.png");
        Image ic5 = ic4.getImage().getScaledInstance(jb.getWidth(), jb.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic6 = new ImageIcon(ic5);
        jb.setIcon(ic6);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(102, 0, 102));
        jButton1.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 204, 255));
        jButton1.setText("SEND OTP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1090, 250, 190, 50);

        jButton2.setBackground(new java.awt.Color(102, 0, 102));
        jButton2.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 204, 255));
        jButton2.setText("GET PASSWORD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1070, 450, 250, 50);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 101, 75));
        jLabel1.setText("EMAIL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(700, 170, 200, 50);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 101, 75));
        jLabel2.setText("OTP RECEIVED");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(590, 360, 380, 50);

        tf1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tf1.setForeground(new java.awt.Color(153, 153, 153));
        tf1.setText("ENTER EMAIL...");
        tf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf1FocusLost(evt);
            }
        });
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(1040, 170, 330, 50);

        tf2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tf2.setForeground(new java.awt.Color(153, 153, 153));
        tf2.setText("ENTER OTP ...");
        tf2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf2FocusLost(evt);
            }
        });
        getContentPane().add(tf2);
        tf2.setBounds(1030, 350, 330, 50);

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Segoe Script", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(245, 101, 75));
        jLabel3.setText("FORGOT PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(780, 80, 580, 50);

        jb.setBackground(new java.awt.Color(245, 101, 75));
        jb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActionPerformed(evt);
            }
        });
        getContentPane().add(jb);
        jb.setBounds(20, 30, 100, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String email=tf1.getText();
        try {
            rs=DBloader.executeSQL("select * from user where email='"+ email + "'");
            if(rs.next())
            {
                 otp =  (int) (1000+(9999-1000)*Math.random())+"";
                sendemail obj=new sendemail(email, "Password recovery", "Your OTp is"+otp);
                obj.sendemail();
                //JOptionPane.showMessageDialog(this, "OTP Sent");
                
                UIManager.put("OptionPane.messageFont", new Font("Brush Script MT", Font.BOLD, 18));
                        UIManager.put("OptionPane.messageForeground", Color.RED);
                        JOptionPane.showMessageDialog(rootPane, "OTP SENT !!", "FORGOT PASSWORD ", JOptionPane.INFORMATION_MESSAGE);
                
                
                jLabel2.setVisible(true);
                tf2.setVisible(true);
                jButton2.setVisible(true);
            }
            else
            {
                
                UIManager.put("OptionPane.messageFont", new Font("Brush Script MT", Font.BOLD, 18));
                        UIManager.put("OptionPane.messageForeground", Color.RED);
                        JOptionPane.showMessageDialog(rootPane, "EMAIL NOT REGISTERED!!", "FORGOT PASSWORD BOX ", JOptionPane.INFORMATION_MESSAGE);
               // JOptionPane.showMessageDialog(this, "Email not registered");
            }
        } catch (Exception ex) {
            //Logger.getLogger(forgot_password.class.getName()).log(Level.SEVERE, null, ex);
        ex.printStackTrace();}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String otp2=tf2.getText();
        if(otp2.equals(otp))
        {
            try {
               String pass= rs.getString("password");
               
               UIManager.put("OptionPane.messageFont", new Font("Brush Script MT", Font.BOLD, 18));
                        UIManager.put("OptionPane.messageForeground", Color.RED);
                       // JOptionPane.showMessageDialog(rootPane, "FAV ADDED!!", "FAVOURITE BOX ", JOptionPane.INFORMATION_MESSAGE);
               JOptionPane.showMessageDialog(this, "Your password is "+pass);
               
               
               dispose();
              user_login obj=new user_login();
               obj.setVisible(true);
            } catch (SQLException ex) {
               // Logger.getLogger(forgot_password.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"OTP Invalid");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActionPerformed
        // TODO add your handling code here:
         user_login obj = new user_login();
        setVisible(true);
        dispose();
    }//GEN-LAST:event_jbActionPerformed

    private void tf2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf2FocusGained
        // TODO add your handling code here:
         if(tf2.getText().equals("ENTER OTP ..."))
        {
            tf2.setText("");
            tf2.setForeground(Color.BLACK);
        }
      
        
    }//GEN-LAST:event_tf2FocusGained

    private void tf2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf2FocusLost
        // TODO add your handling code here:
         if(tf2.getText().equals(""))
        {
            tf2.setText("ENTER OTP ...");
            tf2.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tf2FocusLost

    private void tf1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf1FocusGained
        // TODO add your handling code here:
        
        
//        if (jTextField1.getText().equals("SEARCH HERE...")) {
//            jTextField1.setText("");
//            jTextField1.setForeground(Color.BLACK);
//        }
        
        
         if(tf1.getText().equals("ENTER EMAIL..."))
        {
            tf1.setText("");
            tf1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tf1FocusGained

    private void tf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf1FocusLost
        // TODO add your handling code here:
         if(tf1.getText().equals(""))
        {
            tf1.setText("ENTER EMAIL...");
            tf1.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tf1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jb;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
