
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DELL
 */
public class home_page extends javax.swing.JFrame {

    /**
     * Creates new form intro
     */
    JLabel plb;

    public home_page() {
        initComponents();

        plb1.setIcon(resize("src/myuploads/lahore.jpg"));
        plb2.setIcon(resize("src/myuploads/m2.jpg"));
        plb3.setIcon(resize("src/myuploads/m3.jpeg"));
        plb4.setIcon(resize("src/myuploads/m10.jpg"));
        plb5.setIcon(resize("src/myuploads/m9.jpg"));
        plb6.setIcon(resize("src/myuploads/m7.jpg"));
        plb7.setIcon(resize("src/myuploads/m8.jpg"));
        plb8.setIcon(resize("src/myuploads/m14.jpg"));
        plb9.setIcon(resize("src/myuploads/mm.jpg"));
        plb10.setIcon(resize("src/myuploads/m13.jpg"));
        plb11.setIcon(resize("src/myuploads/m6.jpg"));
        plb12.setIcon(resize("src/myuploads/m15.jpg"));
        
        jButton4.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
        jButton4FocusGained(evt);
    }
});
        
        
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int h = (int) d.getHeight();
        int w = (int) d.getWidth();

//        plb = new JLabel();
//        plb.setBounds(0, 0, w, h);
//        ImageIcon ic = new ImageIcon("src\\myuploads\\humtv.png");
//        Image ic1 = ic.getImage().getScaledInstance(plb.getWidth(), plb.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon ic2 = new ImageIcon(ic1);
//        plb.setIcon(ic2);
//        add(plb);


        plb = new JLabel();
        plb.setBounds(0, 0, w, h);
        ImageIcon ic = new ImageIcon("src\\myuploads\\12346.jpg");
        Image ic1 = ic.getImage().getScaledInstance(plb.getWidth(), plb.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic2 = new ImageIcon(ic1);
        plb.setIcon(ic2);
        add(plb);

    
        
        
        
// ImageIcon ic11 = new ImageIcon("src\\myuploads\\search.png");
//        Image ic12 = ic11.getImage().getScaledInstance(slb.getWidth(), slb.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon ic13 = new ImageIcon(ic12);
//        slb1.setIcon(ic13);
        ImageIcon ic21 = new ImageIcon("src\\myuploads\\search.png");
        Image ic22 = ic21.getImage().getScaledInstance(slb1.getWidth(), slb1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic23 = new ImageIcon(ic22);
        slb1.setIcon(ic23);

//               
//        lb.setBounds(0,0,w, h);
//        ImageIcon ic = new ImageIcon("src\\myuploads\\black.png");
//        Image ic1 = ic.getImage().getScaledInstance(lb.getWidth(),lb.getHeight(),Image.SCALE_SMOOTH);
//        ImageIcon ic2 = new ImageIcon(ic1);
//        lb.setIcon(ic2);
//        add(lb);
        setSize(w, h);
        setVisible(true);
        //dispose not on login and homepage signup design 

        ImageIcon ic4 = new ImageIcon("src\\myuploads\\FAVOURITE MOVIE1.png");
        Image ic5 = ic4.getImage().getScaledInstance(jButton5.getWidth(), jButton5.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic6 = new ImageIcon(ic5);
        jButton5.setIcon(ic6);
        ImageIcon ic7 = new ImageIcon("src\\myuploads\\FAVOURITE tv.png");
        Image ic8 = ic7.getImage().getScaledInstance(jButton9.getWidth(), jButton9.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic9 = new ImageIcon(ic8);
        jButton9.setIcon(ic9);
    }

    ImageIcon resize(String path) {
        ImageIcon ic = new ImageIcon(path);
        Image img = ic.getImage().getScaledInstance(plb7.getWidth(), plb7.getHeight(), Image.SCALE_SMOOTH);
        //donot create for every image as labels are equal (copy pasted)....
        ImageIcon im = new ImageIcon(img);
        return im;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mlb1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        bt1 = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        plb7 = new javax.swing.JLabel();
        plb8 = new javax.swing.JLabel();
        plb9 = new javax.swing.JLabel();
        plb10 = new javax.swing.JLabel();
        plb11 = new javax.swing.JLabel();
        plb12 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        bt3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        plb1 = new javax.swing.JLabel();
        plb2 = new javax.swing.JLabel();
        plb3 = new javax.swing.JLabel();
        plb4 = new javax.swing.JLabel();
        plb6 = new javax.swing.JLabel();
        plb5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        slb1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bt2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 102));
        getContentPane().setLayout(null);

        mlb1.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        mlb1.setForeground(new java.awt.Color(255, 0, 0));
        mlb1.setText(" MOVIE CENTRAL");
        getContentPane().add(mlb1);
        mlb1.setBounds(10, 20, 410, 70);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("SEARCH HERE...");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(1120, 120, 270, 50);

        bt1.setBackground(new java.awt.Color(255, 60, 105));
        bt1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        bt1.setForeground(new java.awt.Color(255, 255, 255));
        bt1.setText("GO!!");
        bt1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bt1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bt1FocusLost(evt);
            }
        });
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(1400, 120, 110, 50);

        lb1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setText("TOP UPCOMING MOVIES");
        getContentPane().add(lb1);
        lb1.setBounds(20, 190, 430, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        plb7.setText("pic2");
        jPanel1.add(plb7);
        plb7.setBounds(20, 20, 220, 200);

        plb8.setText("pic4");
        jPanel1.add(plb8);
        plb8.setBounds(260, 20, 220, 200);

        plb9.setText("pic5");
        jPanel1.add(plb9);
        plb9.setBounds(500, 20, 220, 200);

        plb10.setText("pic6");
        jPanel1.add(plb10);
        plb10.setBounds(740, 20, 220, 200);

        plb11.setText("pic1");
        jPanel1.add(plb11);
        plb11.setBounds(980, 20, 220, 200);

        plb12.setText("pic 6");
        jPanel1.add(plb12);
        plb12.setBounds(1220, 20, 220, 200);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 550, 1470, 240);

        lb2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lb2.setForeground(new java.awt.Color(255, 255, 255));
        lb2.setText("TOP RATED MOVIES");
        getContentPane().add(lb2);
        lb2.setBounds(30, 500, 360, 40);

        bt3.setBackground(new java.awt.Color(255, 60, 105));
        bt3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt3.setForeground(new java.awt.Color(255, 255, 255));
        bt3.setText("BROWSE");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt3);
        bt3.setBounds(400, 500, 140, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        plb1.setText("pic1");
        jPanel2.add(plb1);
        plb1.setBounds(20, 20, 220, 200);

        plb2.setText("=pic2");
        jPanel2.add(plb2);
        plb2.setBounds(260, 20, 220, 200);

        plb3.setText("pic3");
        jPanel2.add(plb3);
        plb3.setBounds(500, 20, 220, 200);

        plb4.setText("pic5");
        jPanel2.add(plb4);
        plb4.setBounds(740, 20, 220, 200);

        plb6.setText("pic 6");
        jPanel2.add(plb6);
        plb6.setBounds(1220, 20, 220, 200);

        plb5.setText("pic 6");
        jPanel2.add(plb5);
        plb5.setBounds(980, 20, 220, 200);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 240, 1470, 240);

        jScrollPane1.setBackground(new java.awt.Color(98, 37, 105));
        jScrollPane1.setForeground(new java.awt.Color(98, 37, 105));

        jPanel3.setBackground(new java.awt.Color(0, 128, 128));
        jPanel3.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 153, 165));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton1.setText("TV");
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton1FocusGained(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(220, 10, 190, 50);

        jButton2.setBackground(new java.awt.Color(255, 153, 165));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton2.setText("Actor");
        jButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton2FocusGained(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(420, 10, 180, 50);

        jButton3.setBackground(new java.awt.Color(255, 153, 165));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton3.setText("Movie House");
        jButton3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton3FocusGained(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(610, 10, 240, 50);

        jButton4.setBackground(new java.awt.Color(255, 153, 165));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton4.setText("Movie");
        jButton4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton4FocusGained(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(20, 10, 190, 50);

        slb1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel3.add(slb1);
        slb1.setBounds(870, 10, 70, 50);

        jScrollPane1.setViewportView(jPanel3);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 950, 70);

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(480, 10, 160, 85);

        jButton6.setBackground(new java.awt.Color(255, 69, 69));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(236, 219, 186));
        jButton6.setText("EDIT PROFILE ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(820, 20, 210, 60);

        jButton7.setBackground(new java.awt.Color(255, 69, 69));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(236, 219, 186));
        jButton7.setText("CHANGE PASSWORD");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(1040, 20, 270, 60);

        jButton8.setBackground(new java.awt.Color(139, 154, 70));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton8.setForeground(new java.awt.Color(238, 238, 238));
        jButton8.setText("LOG OUT ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(1320, 20, 210, 60);

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(650, 10, 160, 85);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("--------------------------------------------------------------------------------------------------------------------------------------------------------------");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 170, 1550, 25);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("--------------------------------------------------------------------------------------------------------------------------------------------------------------");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 85, 1610, 32);

        bt2.setBackground(new java.awt.Color(255, 60, 105));
        bt2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt2.setForeground(new java.awt.Color(255, 255, 255));
        bt2.setText("BROWSE");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(470, 190, 150, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        top_upcoming obj = new top_upcoming();
        obj.setVisible(true);
        dispose();
        //add [pictures heart  in top upcomimg and top rated 

    }//GEN-LAST:event_bt2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String ans = "Movie";
        search_movies obj = new search_movies(ans);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ans = "TV";
        search_movies obj = new search_movies(ans);
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String ans = "Actor";
        search_movies obj = new search_movies(ans);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String ans = "Movie_House";
        search_movies obj = new search_movies(ans);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:

        String name = jTextField1.getText();
        name = name.replace(" ", "%20");
        search_movies obj = new search_movies(name);
        obj.setVisible(true);
        obj.jt.setVisible(false);
        obj.bt.setVisible(false);
//       dispose();
//            bt.setVisible(false);
    }//GEN-LAST:event_bt1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jTextField1ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        top_rated_movies obj = new top_rated_movies();
        dispose();

        //add heart pictures 
    }//GEN-LAST:event_bt3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String ans = "movie";
        Favourites obj = new Favourites(ans);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        edit_profile obj = new edit_profile();
        dispose();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        change_password obj = new change_password();
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        global.email = "";
        user_login obj1 = new user_login();
        dispose();

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String ans = "tv";
        Favourites obj = new Favourites(ans);
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        if (jTextField1.getText().equals("SEARCH HERE...")) {
            jTextField1.setText("");
            jTextField1.setForeground(Color.BLACK);
        }


    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        if (jTextField1.getText().equals("")) {
            jTextField1.setText("SEARCH HERE...");
            jTextField1.setForeground(Color.GRAY);
        }

    }//GEN-LAST:event_jTextField1FocusLost

    private void jButton4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton4FocusGained
        // TODO add your handling code here:
        jButton4.setBackground(new Color(255,99,71));
    }//GEN-LAST:event_jButton4FocusGained

    private void jButton1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusGained
        // TODO add your handling code here:
        jButton1.setBackground(new Color(255,99,71));
    }//GEN-LAST:event_jButton1FocusGained

    private void jButton2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusGained
        // TODO add your handling code here:
        jButton2.setBackground(new Color(255,99,71));
    }//GEN-LAST:event_jButton2FocusGained

    private void jButton3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton3FocusGained
        // TODO add your handling code here:
        jButton3.setBackground(new Color(255,99,71));
    }//GEN-LAST:event_jButton3FocusGained

    private void bt1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bt1FocusGained
        // TODO add your handling code here:
        bt1.setBackground(new Color(255,153,165));
        bt1.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_bt1FocusGained

    private void bt1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bt1FocusLost
        // TODO add your handling code here:
         bt1.setBackground(new Color(255,60,105));
         bt1.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_bt1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel mlb1;
    private javax.swing.JLabel plb1;
    private javax.swing.JLabel plb10;
    private javax.swing.JLabel plb11;
    private javax.swing.JLabel plb12;
    private javax.swing.JLabel plb2;
    private javax.swing.JLabel plb3;
    private javax.swing.JLabel plb4;
    private javax.swing.JLabel plb5;
    private javax.swing.JLabel plb6;
    private javax.swing.JLabel plb7;
    private javax.swing.JLabel plb8;
    private javax.swing.JLabel plb9;
    private javax.swing.JLabel slb1;
    // End of variables declaration//GEN-END:variables
}
