
import VMM.DBloader;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DELL
 */
public class user_login extends javax.swing.JFrame {

    public user_login() {
        initComponents();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int h = (int) d.getHeight();
        int w = (int) d.getWidth();
        setSize(w, h);
        setVisible(true);
        loadAndSetImage();

        ImageIcon ic4 = new ImageIcon("src\\myuploads\\vgood movie.jpg");
        Image ic5 = ic4.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic6 = new ImageIcon(ic5);
        jLabel2.setIcon(ic6);
        ImageIcon ic41 = new ImageIcon("src\\myuploads\\movie3.jpg");
        Image ic51 = ic41.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic61 = new ImageIcon(ic51);
        jLabel4.setIcon(ic61);

        // Add a component listener to adjust the image size when the label size changes
        jLabel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                loadAndSetImage();
            }
        });
    }

    // Method to load and set the image
    private void loadAndSetImage() {
        ImageIcon originalIcon = new ImageIcon("src/myuploads/mc1.png");
        Image originalImage = originalIcon.getImage();
        int width = jLabel2.getWidth();
        int height = jLabel2.getHeight();
        Image resizedImage = originalImage.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon resizedIcon = new ImageIcon(resizedImage);
        jLabel2.setIcon(resizedIcon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jp1 = new javax.swing.JPasswordField();
        bt1 = new javax.swing.JButton();
        mlb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lb1.setForeground(new java.awt.Color(51, 0, 51));
        lb1.setText("EMAIL");
        getContentPane().add(lb1);
        lb1.setBounds(910, 120, 180, 50);

        lb2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lb2.setForeground(new java.awt.Color(51, 51, 0));
        lb2.setText("PASSWORD");
        getContentPane().add(lb2);
        lb2.setBounds(840, 190, 210, 50);

        tf1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(tf1);
        tf1.setBounds(1100, 130, 270, 40);

        jp1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jp1ActionPerformed(evt);
            }
        });
        getContentPane().add(jp1);
        jp1.setBounds(1100, 190, 270, 40);

        bt1.setBackground(new java.awt.Color(255, 51, 51));
        bt1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bt1.setForeground(new java.awt.Color(255, 255, 255));
        bt1.setText("LOGIN");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(990, 290, 180, 50);

        mlb.setBackground(new java.awt.Color(51, 51, 255));
        mlb.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        mlb.setForeground(new java.awt.Color(255, 0, 51));
        mlb.setText("LOGIN");
        getContentPane().add(mlb);
        mlb.setBounds(1110, 40, 170, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setText("IF NOT HAVE AN ACCOUNT ? ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(980, 380, 340, 40);

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SIGN - UP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1030, 450, 210, 50);

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("FORGOT PASSWORD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1250, 290, 270, 50);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 750, 890);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 780, 780);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(750, 0, 840, 890);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        try {
            String email = tf1.getText();
            String password = new String(jp1.getPassword());
            ResultSet rs = DBloader.executeSQL("select * from user where email ='" + email + "'and password ='" + password + "'");
            if (rs.next()) {
                UIManager.put("OptionPane.messageFont", new Font("Brush Script MT", Font.BOLD, 18));
                UIManager.put("OptionPane.messageForeground", Color.RED);
                JOptionPane.showMessageDialog(this, "**LOGIN SUCCESSFUL**", "LOGIN ALERT ", JOptionPane.INFORMATION_MESSAGE);
                global.email = email;
                home_page hm = new home_page();

            } else {
                UIManager.put("OptionPane.messageFont", new Font("Arial", Font.BOLD, 18));
                UIManager.put("OptionPane.messageForeground", Color.RED); // Optional: change text color
                // UIManager.put("OptionPane.background", Color.WHITE); 
                //UIManager.put("Panel.background", Color.WHITE); 
                JOptionPane.showMessageDialog(this, "**LOGIN CREDENTIALS NOT VALID**  ", "LOGIN ALERT ", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bt1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        user_signup obj = new user_signup();
        obj.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        forgot_password obj = new forgot_password();
        obj.setVisible(true);
        // dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jp1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jp1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel mlb;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
