
import VMM.DBloader;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.*;
import javax.swing.JFileChooser;
import java.sql.*;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class user_signup extends javax.swing.JFrame {

    /**
     * Creates new form user_signup
     */
    JLabel lb;
    
    public user_signup() {
        initComponents();
        
        // lb6.setFont(new java.awt.Font("Segoe UI", 0, 20)); 
          
        
        getContentPane().setBackground(new java.awt.Color(240, 240, 240));
//        lb1.setForeground(new java.awt.Color(102, 0, 102));
//        lb2.setForeground(new java.awt.Color(102, 0, 102));
//        lb3.setForeground(new java.awt.Color(102, 0, 102));
//        lb4.setForeground(new java.awt.Color(102, 0, 102));
//        lb5.setForeground(new java.awt.Color(102, 0, 102));
//        lb6.setForeground(new java.awt.Color(102, 0, 102));
//        mb1.setForeground(new java.awt.Color(255, 51, 51));
//        bt1.setForeground(new java.awt.Color(255, 0, 0));
       // jPanel.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 2));
        
        

        // Set the container panel as the content pane
      
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
          int h=(int)d.getHeight();
          int w=(int)d.getWidth();
          setSize(w,h);
            setLocationRelativeTo(null);
            setVisible(true);
//            loadAndSetImage();
            lb=new JLabel();
             lb.setBounds(0, 0, w, h);
    
            
            ImageIcon ic = new ImageIcon("src\\myuploads\\popcorn.jpg");
    Image ic1 = ic.getImage().getScaledInstance(lb.getWidth(), lb.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon ic2 = new ImageIcon(ic1);
    lb.setIcon(ic2);
    ImageIcon ic4 = new ImageIcon("src\\myuploads\\left-arrow1.png");
        Image ic5 = ic4.getImage().getScaledInstance(jButton1.getWidth(), jButton1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic6 = new ImageIcon(ic5);
        jButton1.setIcon(ic6);
    
    add(lb);
        setVisible(true);
        setSize(w,h);
// jLabel2.addComponentListener(new java.awt.event.ComponentAdapter() {
//            public void componentResized(java.awt.event.ComponentEvent evt) {
//                loadAndSetImage();
//            }
//        });
//    }

    // Method to load and set the image
//    private void loadAndSetImage() {
//        ImageIcon originalIcon = new ImageIcon("src\\myuploads\\popcorn.jpg");
//        Image originalImage = originalIcon.getImage();
//        int width = jLabel2.getWidth();
//        int height = jLabel2.getHeight();
//        Image resizedImage = originalImage.getScaledInstance(width, height, Image.SCALE_SMOOTH);
//        ImageIcon resizedIcon = new ImageIcon(resizedImage);
//        jLabel2.setIcon(resizedIcon);
//    
    
    }

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mlb1 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        mb1 = new javax.swing.JButton();
        tf1 = new javax.swing.JTextField();
        jp1 = new javax.swing.JPasswordField();
        tf2 = new javax.swing.JTextField();
        jp2 = new javax.swing.JPasswordField();
        photo = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();
        tf3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));
        getContentPane().setLayout(null);

        mlb1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        mlb1.setForeground(new java.awt.Color(255, 51, 51));
        mlb1.setText("SIGN UP");
        getContentPane().add(mlb1);
        mlb1.setBounds(710, 10, 260, 50);

        lb1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 51));
        lb1.setText("NAME");
        getContentPane().add(lb1);
        lb1.setBounds(490, 90, 160, 40);

        lb2.setBackground(new java.awt.Color(0, 204, 204));
        lb2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lb2.setForeground(new java.awt.Color(255, 255, 51));
        lb2.setText("PASSWORD");
        getContentPane().add(lb2);
        lb2.setBounds(420, 160, 250, 40);

        lb3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lb3.setForeground(new java.awt.Color(255, 255, 51));
        lb3.setText("CONFIRM PASSWORD");
        getContentPane().add(lb3);
        lb3.setBounds(340, 210, 410, 50);

        lb4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lb4.setForeground(new java.awt.Color(255, 255, 51));
        lb4.setText("MOBILE NO.");
        getContentPane().add(lb4);
        lb4.setBounds(430, 270, 250, 50);

        lb5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lb5.setForeground(new java.awt.Color(255, 255, 51));
        lb5.setText("EMAIL");
        getContentPane().add(lb5);
        lb5.setBounds(480, 340, 140, 40);

        lb6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lb6.setForeground(new java.awt.Color(102, 0, 102));
        lb6.setText("PHOTO");
        getContentPane().add(lb6);
        lb6.setBounds(1130, 100, 150, 40);

        mb1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mb1.setForeground(new java.awt.Color(255, 51, 51));
        mb1.setText("SUBMIT");
        mb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb1ActionPerformed(evt);
            }
        });
        getContentPane().add(mb1);
        mb1.setBounds(660, 420, 360, 50);

        tf1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(760, 100, 220, 40);

        jp1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jp1ActionPerformed(evt);
            }
        });
        getContentPane().add(jp1);
        jp1.setBounds(760, 160, 220, 40);

        tf2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf2);
        tf2.setBounds(760, 280, 220, 40);

        jp2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jp2ActionPerformed(evt);
            }
        });
        getContentPane().add(jp2);
        jp2.setBounds(760, 220, 220, 40);
        getContentPane().add(photo);
        photo.setBounds(1100, 180, 240, 210);

        bt1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bt1.setForeground(new java.awt.Color(255, 0, 0));
        bt1.setText("BROWSE");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(1100, 420, 220, 50);

        tf3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });
        getContentPane().add(tf3);
        tf3.setBounds(760, 340, 220, 40);

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 30, 100, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    


    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf3ActionPerformed

    private void jp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jp1ActionPerformed

    private void jp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jp2ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed
          File ph;
  
    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        JFileChooser jfc=new JFileChooser();
        int ans=jfc.showOpenDialog(this);
        if(ans==JFileChooser.APPROVE_OPTION)
        {
           ph=jfc.getSelectedFile();
            ImageIcon ic=new ImageIcon(ph.getPath());
            Image ic1=ic.getImage().getScaledInstance(photo.getWidth(), photo.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon ic2=new ImageIcon(ic1);
            photo.setIcon(ic2);
        }
    }//GEN-LAST:event_bt1ActionPerformed
  private boolean isValidEmail(String email) {
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
        Pattern emailPattern = Pattern.compile(emailRegex);
        return emailPattern.matcher(email).matches();
    }
    private void mb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb1ActionPerformed
             String name = tf1.getText();
             String password = jp1.getText();
             String cp= jp2.getText();
             String contact= tf2.getText();
             String email= tf3.getText();  
//             if (isValidEmail(email)) {
//        // Proceed with registration if email is valid
//        System.out.println("Email is valid. Proceed with registration.");
//        // Add your code to handle other form fields and save user details
//            
//            } else {
//        // Show error message if email is invalid
//        JOptionPane.showMessageDialog(null, "Invalid email address. Please enter a valid email.");
//    } 
//      
  
         try{
             if (isValidEmail(email)) {
        // Proceed with registration if email is valid
        System.out.println("Email is valid. Proceed with registration.");
        // Add your code to handle other form fields and save user details
        ResultSet rs=DBloader.executeSQL("select * from user where email='"+email+"'");
             JOptionPane.showMessageDialog(this, "Your Account has been Created");
                 tf1.setText("");
                 tf2.setText("");
                 tf3.setText("");
                 jp1.setText("");
                 jp2.setText("");
                 photo.setIcon(null);
//               ResultSet rs=DBloader.executeSQL("select * from user where email='"+email+"'");
               if(rs.next())
           {

                     JOptionPane.showMessageDialog(this, "Email Already Exist");
           }
           else
           {
             String path=SaveFile.saveFile(ph);
             rs.moveToInsertRow();
             rs.updateString("email", email);
             rs.updateString("username", name);
             rs.updateString("password", password);
             rs.updateString("contact", contact);
             rs.updateString("photo", path);
             rs.insertRow();
           }
}

             else {
        // Show error message if email is invalid
        JOptionPane.showMessageDialog(null, "Invalid email address. Please enter a valid email.");
    }
//             if (isValidEmail(email)) {
//        // Proceed with registration if email is valid
//        System.out.println("Email is valid. Proceed with registration.");
//        // Add your code to handle other form fields and save user details
//             JOptionPane.showMessageDialog(this, "Your Account has been Created");
//                 tf1.setText("");
//                 tf2.setText("");
//                 tf3.setText("");
//                 jp1.setText("");
//                 jp2.setText("");
//            } else {
//        // Show error message if email is invalid
//        JOptionPane.showMessageDialog(null, "Invalid email address. Please enter a valid email.");
//    } 
      
//                 JOptionPane.showMessageDialog(this, "Your Account has been Created");
//                 tf1.setText("");
//                 tf2.setText("");
//                 tf3.setText("");
//                 jp1.setText("");
//                 jp2.setText("");
                 

           }
              
         catch(Exception ex)
          {
             ex.printStackTrace();
          }
             
             
             
    }//GEN-LAST:event_mb1ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        user_login obj=new user_login();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jp1;
    private javax.swing.JPasswordField jp2;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JButton mb1;
    private javax.swing.JLabel mlb1;
    private javax.swing.JLabel photo;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    // End of variables declaration//GEN-END:variables
}
